### PR TITLE
Create Arabic Localizable.strings

### PR DESCRIPTION
**Pull request by Mahabmn**

### CODE REVIEW

**Comment by daisukes** [comment]
Hi @Mahabmn, thank you for your contribution!

Before merging I need to ask you two things.

1. Could you please read the [How can I contribute?](https://github.com/hulop/00Readme#how-can-i-contribute) section and follow the instructions. It is related to copyright.
2. Could you tell me a little bit about your project background?

**Comment by Mahabmn** [comment]
> Hi @Mahabmn, thank you for your contribution!
> 
> Before merging I need to ask you two things.
> 
> 1. Could you please read the [How can I contribute?](https://github.com/hulop/00Readme#how-can-i-contribute) section and follow the instructions. It is related to copyright.
> 2. Could you tell me a little bit about your project background?

Hello , thank you for providing me the link I will check it and follow the steps , 
about my project , I have a graduation to create an arabic version of NavCog.

**Comment by Mahabmn** [comment]
hello I have update the pull request and send the CONTRIBUTOR LICENSE AGREEMENT (CLA) to the identified email in the document .

**Comment by daisukes** [comment]
Thank you for updating PR #4 and your project description. I will close this PR.
By the way, which commit of NavCogIOSv3 are you using? Recently (about one month ago), I've updated NavCogIOSv3 and it refers swift-package branch of this repository.

**Comment by Mahabmn** [comment]
thank you 

Regarding NavCogIOS3 , thank you for updating me because I was using an old version .

**Comment by daisukes** [comment]
Are you using XCode12?

**Comment by Mahabmn** [comment]
I am using XCode13

**Pull request closed without merging**
