### PR TITLE
Create Localizable.strings

### PR DESCRIPTION
**Pull request by Mahabmn**
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the open source license
           indicated in the file; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

Signed-off-by: Maha Najm (Maha.b.najm@gmail.com)

### CODE REVIEW

**Comment by daisukes** [comment]
You need to refer to the new Localizable.string file from the Xcode project.
https://developer.apple.com/documentation/xcode/adding-support-for-languages-and-regions

**Comment by Mahabmn** [comment]
ok , I will create new pull request

**Comment by daisukes** [comment]
Hello @Mahabmn,

You don't need to make a new PR when you've updated the code. 
You can just commit and push to your branch (Mahabmn:my-new-feature) which you used to create the original PR. When you push new commits to the branch, the PR will be automatically updated. It is also helpful for me to track the comments. 

What I wanted you to do is to integrate the localizable string file into the project.

I updated the master branch so that you can test your string with `HLPDialogTest` target.
https://github.com/hulop/HLPDialog/commit/561690457748408b958a2bb95b095661175342e6
You may need to run the test app with your physical device if you use M1 mac. With intel mac, you may be able to run the test app on the simulator.

### How to run the HLPDialogTest with your target language

1. select HLPDialogTest at the top of the Xcode view
2. select device or simulator
3. click HLPDialogTest and select Edit Scheme...
4. in Options tab, select your language for the App language
5. Launch the app

Your goal is to make your language string available on the screen. This screen will show up when you tap the mic icon at the left bottom of the initial screen. The attached screen is the screen of Japanese. 

Screen Shot 2022-04-04 at 4 48 23 PM

Thank you

**Comment by Mahabmn** [comment]
Arabic

hello , I update the package with the arabic localization , what is the next step  , thank you

**Comment by daisukes** [comment]
It looks good! I will review the changes when you push new commits.

Btw, is the side of the baloons okay?
- left: system messages
- right: user input

Back button is shown at the right side which is opposite from English or Japanese, so I just wondered if the messages sides (left/right) are natural for Arabic.

**Comment by Mahabmn** [comment]
hello 
balloons is okay , for the back button is in the right due to arabic language . 

I will push the new commits . 

thank you

**Comment by Mahabmn** [comment]
hello , I push the new update , did you have any comments

**Comment by daisukes** [comment]
Hmm, I need changes you made to obtain your Arabic text screenshots.
You should have updated `HLPDialog.xcodeproj/project.pbxproj` file to refer your `HLPDialog/Ar.lproj/Localizable.strings` file.
I can not make the Arabic screenshot view with this branch.

Please let me know if you need help to include the change.
**Note: when you include `HLPDialog.xcodeproj/project.pbxproj`, don't include your Development Team ID.**

**Comment by Mahabmn** [comment]
hello , I upload the new file , but I receive a conflict file message

**Comment by Mahabmn** [comment]
hello , I push the new update , did you have any comments

**Comment by daisukes** [comment]
As you mentioned earlier, since the project file has some conflicts, I can't merge it.
Moreover, the project file has irrelevant changes like a swift-package declaration.

May I fix the issue?

**Comment by Mahabmn** [comment]
hello , yes of course , you can fix it . 
thank you

**Comment by daisukes** [comment]
Hi @Mahabmn, 

I push some changes.
You may need to build with the workaround for Carthage Xcode13.
https://github.com/Carthage/Carthage/issues/3201

HLPDialogTest target now can show Arabic language in conversation interface.
Could you translate text in `./HLPDialogTest/ar.lproj/Main.strings` file?

**Comment by Mahabmn** [comment]
hello 
thank you , I will try to build it . 

I will translate it and add the update

**Comment by Mahabmn** [comment]
done the file has been translated

**Comment by daisukes** [comment]
Sorry for my late response.
I will squash and merge the changes.

**Comment by Mahabmn** [comment]
Thank you for your support.

**Pull request merged**
